// 获取书籍内容
export const FETCH_BOOK_CONTENT_REQUEST = 'FETCH_BOOK_CONTENT_REQUEST'
export const FETCH_BOOK_CONTENT_SUCCESS = 'FETCH_BOOK_CONTENT_SUCCESS'
export const FETCH_BOOK_CONTENT_FAILURE = 'FETCH_BOOK_CONTENT_FAILURE'

// 高亮操作
export const ADD_HIGHLIGHT = 'ADD_HIGHLIGHT'
export const REMOVE_HIGHLIGHT = 'REMOVE_HIGHLIGHT'

// 评论操作
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

// 阅读进度
export const UPDATE_READING_PROGRESS = 'UPDATE_READING_PROGRESS'
