name: flutter_reader_app
description: A Flutter reading app similar to WeChat Reading.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.5
  uuid: ^3.0.7
  flutter_html: ^3.0.0-alpha.6
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PingFang SC
      fonts:
        - asset: assets/fonts/PingFang-SC-Regular.ttf
        - asset: assets/fonts/PingFang-SC-Medium.ttf
          weight: 500
        - asset: assets/fonts/PingFang-SC-Bold.ttf
          weight: 700